<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd5028c37e896334c228b819b66ab0249
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Starter\\' => 8,
        ),
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Starter\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd5028c37e896334c228b819b66ab0249::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd5028c37e896334c228b819b66ab0249::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd5028c37e896334c228b819b66ab0249::$classMap;

        }, null, ClassLoader::class);
    }
}
