export const colorOptions = [
  { label: 'None', value: 'none' },
  { label: 'Black', value: 'black' },
  { label: 'White', value: 'white' },
  { label: 'Grey', value: 'grey' },
  { label: 'Orange', value: 'orange' },
  { label: 'Green Dark', value: 'green-dark' },
  { label: 'Green', value: 'green' },
  { label: 'Green 80', value: 'green80' },
  { label: 'Green 60', value: 'green60' },
  { label: 'Green 40', value: 'green40' },
  { label: 'Green 20', value: 'green20' },
  { label: 'Yellow', value: 'yellow' },
  { label: 'Yellow 80', value: 'yellow80' },
  { label: 'Yellow 60', value: 'yellow60' },
  { label: 'Yellow 40', value: 'yellow40' },
  { label: 'Yellow 20', value: 'yellow20' },
  { label: 'Blue', value: 'blue' },
  { label: 'Blue 80', value: 'blue80' },
  { label: 'Blue 60', value: 'blue60' },
  { label: 'Blue 40', value: 'blue40' },
  { label: 'Blue 20', value: 'blue20' },
];
